export const ADD_NAME = "ADD_NAME";
export const FETCH_UNIVERSITIES = "FETCH_UNIVERSITIES";
export const SET_UNIVERSITIES = "SET_UNIVERSITIES";
export const FAILED_FETCHED_UNIVERSITIES = "FAILED_FETCHED_UNIVERSITIES";
export const SELECT_UNIVERSITY = "SELECT_UNIVERSITY";
export const INPUT_NOT_CHANGES = "INPUT_NOT_CHANGES";
export const INPUT_CHANGES = "INPUT_CHANGES";
