export const ADD_NAME = "ADD_NAME";
export const FETCH_UNIVERSITIES = "FETCH_UNIVERSITIES";
export const SET_UNIVERSITIES = "SET_UNIVERSITIES";
export const FAILED_FETCHED_UNIVERSITIES = "FAILED_FETCHED_UNIVERSITIES";
